package com.chui.pos.dtos

enum class PermissionEnum {
    ADJUST_STOCK,
    CREATE_PRODUCTS,
    CREATE_SALES,
    CREATE_USERS,
    DELETE_PRODUCTS,
    HOLD_ORDERS,
    MANAGE_CATEGORIES,
    MANAGE_PERMISSIONS,
    MANAGE_PRODUCTS,
    MANAGE_ROLES,
    MANAGE_STOCK,
    MANAGE_UNITS,
    MANAGE_USERS,
    RESUME_ORDERS,
    UPDATE_PRODUCTS,
    VIEW_PRODUCTS,
    VIEW_SALES_REPORTS,
    VIEW_USERS
}